name: Bygg og deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: create docker tag
        env:
          DOCKER_IMAGE: docker.pkg.github.com/navikt/helse-nl-altinn/helse-nl-altinn
        run: |
          echo $DOCKER_IMAGE > .docker_image
          echo $(echo $GITHUB_SHA | cut -c1-7) > .docker_tag
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: test and build
        run: ./gradlew test build
      - name: build docker image
        run: docker build . --pull -t $(cat .docker_image):$(cat .docker_tag)
      - name: push docker image
        run: |
          echo "$GITHUB_ACCESS_TOKEN" | docker login --username "x-access-token" --password-stdin docker.pkg.github.com
          docker push $(cat .docker_image):$(cat .docker_tag)
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
      - uses: actions/checkout@v1
        with:
          repository: navikt/syfonais.git
          ref: master
          path: syfonais
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
      - name: ls
        run: |
          pwd
          ls -al
          ls -al ../syfonais
          ls -al ../syfonais/preprod-fss/helse-nl-altinn
          cp ../syfonais/preprod-fss/helse-nl-altinn/naiserator.yaml ./
          ls -al
#  deploy:
#    name: NAIS deployment
#    runs-on: ubuntu-latest
#    steps:
      - name: deploy
        uses: navikt/deployment-cli/action@4951123ccd16702b8ed14a4367b8cfba7fc05de1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cluster: dev-fss
          team: teamsykefravr
          resources: naiserator.yaml
